<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        // Password yang sama untuk semua user: "password"
        $password = Hash::make('password');

        $users = [
            // 1. Owner
            [
                'id' => 1,
                'name' => 'Owner Auto2000',
                'email' => 'owner@auto2000.com',
                'role_id' => 1, // Owner
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081234567801',
                'employee_number' => 'OWN001',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1980-01-01',
                'gender' => 'Male',
                'emergency_contact' => '081234567802',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => false,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 2. Admin
            [
                'id' => 2,
                'name' => 'Admin Auto2000',
                'email' => 'admin@auto2000.com',
                'role_id' => 2, // Admin
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081234567811',
                'employee_number' => 'ADM001',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1985-05-15',
                'gender' => 'Female',
                'emergency_contact' => '081234567812',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // --- MECHANIC (17 orang, semua Samarinda) ---
            [
                'id' => 3,
                'name' => 'FILSA GUNAWAN',
                'email' => 'filsa.gunawan@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000001',
                'employee_number' => 'MECH001',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-01-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000001',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'KHANIF CHOERUDIN',
                'email' => 'khanif.choerudin@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000002',
                'employee_number' => 'MECH002',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-02-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000002',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'NOR JAYADI',
                'email' => 'nor.jayadi@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000003',
                'employee_number' => 'MECH003',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-03-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000003',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'CALVIN AFI ANDIKA',
                'email' => 'calvin.afi.andika@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000004',
                'employee_number' => 'MECH004',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-04-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000004',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'ANDRIANTO',
                'email' => 'andrianto@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000005',
                'employee_number' => 'MECH005',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-05-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000005',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'YUWONO PRASOJO',
                'email' => 'yuwono.prasojo@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000006',
                'employee_number' => 'MECH006',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-06-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000006',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'WAHYU SETIAWAN',
                'email' => 'wahyu.setiawan@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000007',
                'employee_number' => 'MECH007',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-07-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000007',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'ABID DHARMA PUTRA',
                'email' => 'abid.dharma.putra@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000008',
                'employee_number' => 'MECH008',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-08-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000008',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'ABDUL RAHIM',
                'email' => 'abdul.rahim@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000009',
                'employee_number' => 'MECH009',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-09-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000009',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'BAMBANG PRAYOGO',
                'email' => 'bambang.prayogo@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000010',
                'employee_number' => 'MECH010',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-10-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000010',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'ZAINUL RAMADAN',
                'email' => 'zainul.ramadan@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000011',
                'employee_number' => 'MECH011',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1990-11-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000011',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'ARYA MAULANA',
                'email' => 'arya.maulana@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000012',
                'employee_number' => 'MECH012',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1991-01-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000012',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'name' => 'SYAMSUL WIJAYANTO',
                'email' => 'syamsul.wijayanto@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000013',
                'employee_number' => 'MECH013',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1991-02-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000013',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'ADIDYA HARI PRASETYO',
                'email' => 'adidya.hari.prasetyo@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000014',
                'employee_number' => 'MECH014',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1991-03-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000014',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'name' => 'ADE ANDRIANA',
                'email' => 'ade.andriana@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000015',
                'employee_number' => 'MECH015',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1991-04-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000015',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'name' => 'ARIS KURNIAWAN',
                'email' => 'aris.kurniawan@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000016',
                'employee_number' => 'MECH016',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1991-05-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000016',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'name' => 'ANDRY APRIYANUR',
                'email' => 'andry.apriyanur@auto2000.com',
                'role_id' => 3,
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081200000017',
                'employee_number' => 'MECH017',
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1991-06-01',
                'gender' => 'Male',
                'emergency_contact' => '081300000017',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // 20. Customer
            [
                'id' => 20,
                'name' => 'Customer Test',
                'email' => 'customer@auto2000.com',
                'role_id' => 4, // Customer
                'email_verified_at' => $now,
                'password' => $password,
                'phone' => '081234567831',
                'employee_number' => null,
                'address' => 'Samarinda, Kalimantan Timur',
                'birthdate' => '1995-12-10',
                'gender' => 'Male',
                'emergency_contact' => '081234567832',
                'avatar' => null,
                'is_active' => true,
                'is_on_duty' => false,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('users')->insert($users);

        // Pivot user_roles (many-to-many)
        $userRoles = [
            ['user_id' => 1, 'role_id' => 1], // Owner
            ['user_id' => 2, 'role_id' => 2], // Admin
            // 3–19 semuanya mekanik
            ['user_id' => 3, 'role_id' => 3],
            ['user_id' => 4, 'role_id' => 3],
            ['user_id' => 5, 'role_id' => 3],
            ['user_id' => 6, 'role_id' => 3],
            ['user_id' => 7, 'role_id' => 3],
            ['user_id' => 8, 'role_id' => 3],
            ['user_id' => 9, 'role_id' => 3],
            ['user_id' => 10, 'role_id' => 3],
            ['user_id' => 11, 'role_id' => 3],
            ['user_id' => 12, 'role_id' => 3],
            ['user_id' => 13, 'role_id' => 3],
            ['user_id' => 14, 'role_id' => 3],
            ['user_id' => 15, 'role_id' => 3],
            ['user_id' => 16, 'role_id' => 3],
            ['user_id' => 17, 'role_id' => 3],
            ['user_id' => 18, 'role_id' => 3],
            ['user_id' => 19, 'role_id' => 3],
            ['user_id' => 20, 'role_id' => 4], // Customer
        ];

        DB::table('user_roles')->insert($userRoles);

        $this->command->info('✅ Users (Owner, Admin, 17 Mechanic, Customer) created successfully!');
        $this->command->warn('📧 Contoh login (password: "password"):');
        $this->command->line('   Owner:    owner@auto2000.com');
        $this->command->line('   Admin:    admin@auto2000.com');
        $this->command->line('   Customer: customer@auto2000.com');
        $this->command->line('   Mechanic: misal filsa.gunawan@auto2000.com');
    }
}
